name: Deploy worker

on:
  workflow_call:
    inputs:
      worker:
        type: string
        required: true
        description: Worker name

jobs:
  deploy:
    name: "Deploy and restart worker ${{ inputs.worker}}"
    runs-on: ubuntu-latest
    steps:
      - name: Process value
        run: echo "Processing value ${{ inputs.worker }}"
