name: Manual deploy all notifications workers
run-name: Manual deploy all notifications workers

on:
  workflow_dispatch:
    inputs:

jobs:
  gw_deploy:
    uses: ./.github/workflows/ci_cd_worker.yml
    secrets: inherit
    strategy:
      matrix:
        value:
          - "notification-events-to-clickhouse-worker"
          - "notification-producer-worker"
          - "notification-adapter-worker"
          - "notification-schedule-group-worker"
          - "notification-schedule-reminder-worker"
          - "notification-move-group-worker"
          - "notification-move-reminder-worker"
          - "notification-filter-notifications-worker"
          - "notification-email-separator-worker"
          - "notification-send-by-firepush-worker"
          - "notification-send-by-klaviyo-worker"
          - "notification-send-by-omnisend-worker"
          - "notification-send-by-postscript-worker"
          - "notification-send-by-pushowl-worker"
          - "notification-send-by-ses-worker"
          - "notification-send-by-shopify-flow-worker"
    with:
      worker: ${{ matrix.value }}
